### ISSUE TITLE
Research not released yet

### ISSUE THREAD

**Issue by nanaBaah** [leggedrobotics/DeLORA#1]

**Comment by nubertj** [comment]
Dear @nanaBaah,
Thanks a lot for your interest in our work. We would also really like to make the code available as soon as possible.
However, unfortunately the corresponding work is currently still under review (for ICRA2021). As written in the description of the repository, the code will be made publicly available upon publication of the paper. Nevertheless, we plan to make it available as soon as the paper is accepted (not waiting for the publication to happen). In the best case this will be in the beginning of March this year. So let's keep our fingers crossed.
I hope you understand our thoughts.
Julian

**Comment by chenpengxin** [comment]
Very interesting work. Is the paper accepted now? We are looking forward to your code.

**Comment by nubertj** [comment]
Dear @chenpengxin,
Thanks for your interest! 
Luckily, the paper go accepted. The code cleaning is done already and we are currently only waiting for the internal ok to open source it. 
So thanks for a few more days of patience ;)
Julian

**Comment by chenpengxin** [comment]
@nubertj 

Congrats !!!  
And very grateful for your contribution on open source.

**Comment by nubertj** [comment]
Hi,
Unfortunately it takes a bit longer than we expected. Hence, we need a bit more time. 
But at max it should be one more week or so.
Sorry for the inconveniences, and thanks a lot for your patience! :)

**Comment by chenpengxin** [comment]
still waiting...

**Comment by nubertj** [comment]
It is open-sourced now. We hope that it provides benefit to the community.
Thanks for your patience!
