### ISSUE TITLE
can not find ./config/config_datasets_preprocessing.yaml

### ISSUE THREAD

**Issue by shenhai911** [leggedrobotics/DeLORA#10]
Dear author,
    I can not find "config_datasets_preprocessing.yaml" in ./config to test my own data, could you please answer this small question? Thank you very much.

**Comment by nubertj** [comment]
Sorry for the wrong instructions.
Corrected it in commit bde890fb3045198da83feb061f62b96599b81c57

Best,
Julian

**Comment by shenhai911** [comment]
> Sorry for the wrong instructions. Corrected it in commit [bde890f](https://github.com/leggedrobotics/DeLORA/commit/bde890fb3045198da83feb061f62b96599b81c57)
> 
> Best, Julian

Ok, thank you very much.

Best,
Shenhai
