### ISSUE TITLE
Failed to load Python extension for LZ4 support

### ISSUE THREAD

**Issue by sunhufly** [leggedrobotics/DeLORA#11]
First of all thank you very much for your work.
When we run 'preprocesser.py', we meet the issues:
Failed to load Python extension for LZ4 support. LZ4 compression will not be available.
could you help me how to solve this problem??

**Comment by nubertj** [comment]
Hi @HSmallYesterday,
If I install the environment from the conda config file and install the environment (pip install -e .) I can both run the scrip preprocess_data.py as well as the class code prepcoesser.py (but which is of course not doing anything).

Can you explain the steps you have taken in more detail?

**Comment by nubertj** [comment]
The conda file also contains installation requirements for lz4 (specifically lz4-c=1.9.3). So if you are not installing the environment correctly, I assume you have to run pip install lz4. 
Please reopen if you still have issues.

Best,
Julian
