### ISSUE TITLE
About Scan2Map

### ISSUE THREAD

**Issue by yuqJin** [leggedrobotics/DeLORA#12]
The experimental results in your paper show that the performance of self-supervised LO+map has improved significantly. Now I have a question to combine the trained odometry with mapping. How did you embed this project in LOAM?

**Comment by cynosure4sure** [comment]
Hi @yuqJin!
We used this implementation of LOAM: https://github.com/laboshinl/loam_velodyne
and in LaserMapping.cpp we switched laser odometry topic "laser_odom_to_init" to our learned odometry topic. You have to take care of some frame transformations as LOAM uses a different frame convention than ROS (Z-forward, X-left and Y-up) and that's about it.

**Comment by hhongwei1009** [comment]
> Hi @yuqJin! We used this implementation of LOAM: https://github.com/laboshinl/loam_velodyne and in LaserMapping.cpp we switched laser odometry topic "laser_odom_to_init" to our learned odometry topic. You have to take care of some frame transformations as LOAM uses a different frame convention than ROS (Z-forward, X-left and Y-up) and that's about it.

Can you be more detailed? Thank you very much!

**Comment by nubertj** [comment]
Hi @hhongwei1009,
Thanks a lot for your message. In what sense are you missing the information? Instead of using the LOAM scan2scan, we were simply using the learned scan2scan. 
Best,
Julian
