### ISSUE TITLE
ValueError: axes don't match array only for ouster lidar

### ISSUE THREAD

**Issue by arkinrc** [leggedrobotics/DeLORA#15]
It's my 2nd time to show this error which occurs only using ouster lidar. kitti dataset where used velodyne lidar and others are working well. however i have ouster lidar and i tried to use darpa SubT dataset but still same issue because of ouster lidar. 

after training custom dataset using Ouster OS1-64E Lidar have got follwoing error when i run
run_rosnode.py --checkpoint /home/arkin/DeLORA/checkpoints/small_epoch_75.pth --dataset darpa --lidar_topic="/os_cloud_node/points" --lidar_frame="os_lidar"

`[ERROR] [1642642253.397553]: bad callback: <bound method OdometryPublisher.subscriber_callback of <ros_utils.odometry_publisher.OdometryPublisher object at 0x7f5404141040>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/arkin/DeLORA/src/ros_utils/odometry_publisher.py", line 188, in subscriber_callback
    self.point_cloud_t = torch.from_numpy(self.filter_scans(point_cloud_t_numpy))
  File "/home/arkin/DeLORA/src/ros_utils/odometry_publisher.py", line 93, in filter_scans
    scan = np.transpose(scan, (2, 1, 0))
  File "<__array_function__ internals>", line 5, in transpose
  File "/home/arkin/anaconda3/envs/DeLORA-py3.9/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 658, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/arkin/anaconda3/envs/DeLORA-py3.9/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array

`

Looking forward to ur feedback. 
Thanks

**Comment by nubertj** [comment]
Hi @arkinrc ,
Sorry for not replying you earlier, I was super busy with deadlines and stuff and lost track of this repository.
Did you sort out the issues you had with Ouster sensor? Was this the reason why you closed the Issue?

For sure I will provide support for the darpa dataset with the ouster sensor,  but if you have custom datasets I could also try to have a look.

Sorry again!

Best,
Julian

**Comment by arkinrc** [comment]
@nubertj  Thanks for your feedback. i tried with Darpa Subt challange dataset link given in this repository and custom dataset as well but both cases was facing the same issue as mentioned in question. now, Yes i solved this issue by down sampling of ouster dataset using pcl and used voxel filter and reconvert it into rosmsg type . however, i don't know whether its correct one or not. if you have different idea please let me know. Thanks....

**Comment by nubertj** [comment]
Dear Arkin,
I will try to run the dataset later and see.
I always used it, so I am a bit surprised. I will keep you updated.
Best,
Julian
