### ISSUE TITLE
multiple gpus error

### ISSUE THREAD

**Issue by arkinrc** [leggedrobotics/DeLORA#18]
Hello, I am trying to use multiple gpus as per given in deployment configuration file. I do have two gpus of Titan RTX 24 GB each but i am unable to use both together however, single gpu can use easily. i've tried different ways but couldn't succeed. error is given below. Might possible gpu selection way is wrong. Could you please guide how to select in proper way. Thanks

`
config["device"] = torch.device(config["device"])
RuntimeError: Invalid device string: 'CUDA_VISIBLE_DEVICES=0,1'

`
Best Regards
Arkin

**Comment by nubertj** [comment]
torch.device() can only be called with "cpu", "cuda" or somethign like "cuda:0" i think if you want to select GPU number one.

The cuda visible devices flag only specifies which GPUs are even visible to your script and can be set by using 
`export CUDA_VISIBLE_DEVICES=0,1`

However, in this code I never trained on multiple GPUs, so I can't provide any support for this.
In general, it is not so difficult, but requries some customization.
