### ISSUE TITLE
About yaml error

### ISSUE THREAD

**Issue by cainiaoshidai** [leggedrobotics/DeLORA#20]
Hi,
    Thanks for your code. 
     When I run `run_training.py` I get a error.

   

>  File "E:/project_1/delora-main/bin/run_training.py", line 97, in <module>
>     trainer.train()
>   File "E:\project_1\delora-main\src\deploy\trainer.py", line 180, in train
>     mlflow.pytorch.log_model(self.model, "latest_model_pickled")
>   File "D:\Anaconda3\envs\torch\lib\site-packages\mlflow\pytorch\__init__.py", line 150, in log_model
>     conda_env=conda_env, code_paths=code_paths, pickle_module=pickle_module, **kwargs)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\mlflow\models\__init__.py", line 77, in log
>     flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\mlflow\pytorch\__init__.py", line 259, in save_model
>     mlflow_model.save(os.path.join(path, "MLmodel"))
>   File "D:\Anaconda3\envs\torch\lib\site-packages\mlflow\models\__init__.py", line 51, in save
>     self.to_yaml(out)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\mlflow\models\__init__.py", line 46, in to_yaml
>     return yaml.safe_dump(self.__dict__, stream=stream, default_flow_style=False)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\__init__.py", line 306, in safe_dump
>     return dump_all([data], stream, Dumper=SafeDumper, **kwds)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\__init__.py", line 278, in dump_all
>     dumper.represent(data)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\representer.py", line 27, in represent
>     node = self.represent_data(data)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\representer.py", line 48, in represent_data
>     node = self.yaml_representers[data_types[0]](self, data)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\representer.py", line 207, in represent_dict
>     return self.represent_mapping('tag:yaml.org,2002:map', data)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\representer.py", line 118, in represent_mapping
>     node_value = self.represent_data(item_value)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\representer.py", line 48, in represent_data
>     node = self.yaml_representers[data_types[0]](self, data)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\representer.py", line 207, in represent_dict
>     return self.represent_mapping('tag:yaml.org,2002:map', data)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\representer.py", line 118, in represent_mapping
>     node_value = self.represent_data(item_value)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\representer.py", line 48, in represent_data
>     node = self.yaml_representers[data_types[0]](self, data)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\representer.py", line 207, in represent_dict
>     return self.represent_mapping('tag:yaml.org,2002:map', data)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\representer.py", line 118, in represent_mapping
>     node_value = self.represent_data(item_value)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\representer.py", line 58, in represent_data
>     node = self.yaml_representers[None](self, data)
>   File "D:\Anaconda3\envs\torch\lib\site-packages\yaml\representer.py", line 231, in represent_undefined
>     raise RepresenterError("cannot represent an object", data)
> yaml.representer.RepresenterError: ('cannot represent an object', '1.10.0')
> 
> Process finished with exit code 1
   
Can you give me some advice?
Thanks.

Best.

**Comment by nubertj** [comment]
Dear @cainiaoshidai,
Thanks a lot for trying out our code, and sorry for the suuuper delayed reply.
I never saw this problem before. It looks like you run the code on Windows, is this possible?

I never did that and hence have no experience with it. 
Unfortunately I can not provide support for issues arising from usage in Windows. If you can reproduce the same problem also on Ubuntu please reopen the issue.
Best,
Julian
