### ISSUE TITLE
About Odom data

### ISSUE THREAD

**Issue by ZYCheng-coder** [leggedrobotics/DeLORA#3]
Thank you very much for your code. When I ran it in ros, I found an error in the odom. The result obtained is the result of each registration, and the odom data calculation is not completed.

**Comment by nubertj** [comment]
Thanks a lot for your comment.
Since we did not do the evaluation in ROS we did not put that much effort into this part, and also the testing on my end was a bit limited in the end.
I will look into it!

**Comment by tomlankhorst** [comment]
@ZYCheng1996 Can you describe the error in detail?
