### ISSUE TITLE
About Preprocessing scan

### ISSUE THREAD

**Issue by XMU-qcj** [leggedrobotics/DeLORA#5]
Thank you very much for your code.
But I have a problem.
When I run preprocess_data.py,I got something mistack.
In Normal_computation.py 
point_neighbors = image[:, v_neighbor_coords, u_neighbor_coords].view(1, 3, -1)
will error report
The shape of the mask [101758] at index 0 does not match the shape of the indexed tensor [3, 64, 2250] a
t index 1

**Comment by nubertj** [comment]
Hi @Unknownnnnnnn,
Which dataset are you using? A private one? Then I can try to reproduce the error.
Best,
Julian
