### ISSUE TITLE
Training a different Lidar dataset with uneven vertical resolution/angular subdivisions.

### ISSUE THREAD

**Issue by nanaBaah** [leggedrobotics/DeLORA#7]
![image](https://user-images.githubusercontent.com/12661590/131841630-93980498-e37b-4820-abc8-9adc95a49584.png)

### Unlike the KITTI dataset with equally spaced angular subdivisions (approximately 0.4) from the Velodyne HDL-64E laser scanner used, I am using a totally different Lidar point cloud dataset with 64 channels (just like Velodyne) but uneven vertical resolution.

1. **How can I use this network to train on a lidar dataset with an uneven vertical resolution?**

2. **How can I change the config files to fix the problem?**

thanks in advance

**Comment by nubertj** [comment]
Hi @nanaBaah ,
I guess in this case you need to think about whether an image is actually the right data representation for you. 
The place of code you would need to change is the ImageProjection. 

In principle the coordinate computation should still work for you: https://github.com/leggedrobotics/DeLORA/blob/909948d63a9517e6dd54bedcf099f6b39ded2cb4/src/utility/projection.py#L21

However, it will also generate non-integer vertical coordinates. Depending on the resolution, you might maybe try to do some interpolation?

Best,
Julian
